FROM node:14
WORKDIR /backend
COPY package*.json ./
# the flag --only=prod will do the work which is required for the production
RUN npm install --only=prod
COPY . ./
EXPOSE 5500
CMD ["npm", "run", "start"]